#!/bin/bash
#

# Activate your conda environment
# replace <your_username> with your actual username to set path correctly
#eval "$(/scratch/<your_username>/icomse_knam_session/miniconda3/bin/conda shell.bash hook)"
#conda activate
#conda activate knamsessionenv
# Set Gaussian to path
#export g16root=/usr/local/gaussian/g16c01_chem_dept
#. $g16root/g16/bsd/g16.profile
 
module load openmpi-5.0.5 # load the openmpi=5 module available on the remote machine
module load gaussian/g09

# Generated by CHARMM-GUI (http://www.charmm-gui.org) v3.7
charmm="/scratch/<user_name>/icomse_knam_session/charmm/install_charmm/bin/charmm" # replace <user_name> with your actual username 
equi_prefix="step4_equilibration"
qmpr_prefix="step4.1_qmmmprep"
prod_prefix="step5_production_gau"
prod_step="step5_gau"
qmpackage="g09"

# Equilibration
#$charmm < "${equi_prefix}.inp" > "${equi_prefix}.out"

# QM/MM input preparation
#$charmm < "${qmpr_prefix}.inp" > "${qmpr_prefix}.out"

# Reaction Specs
rci=-2.0 #initial
rcf=2.0  #final
rcdel=0.1 #spacing
kmin=150 #40
kmax=150

rc_mid=$(awk "BEGIN {print (${rci} + ${rcf})/2}")
winmax=$(awk "BEGIN {print int(((${rcf} - ${rci})/${rcdel}) + 1)}")

# Production Specs
win=1 #CHANGE HERE IF COUNTINUING STARTING WINDOW
#winmax=${win} #UNCOMMENT IF RUNNING ONLY ONE WINDOW 
icnt=1  #CHANGE HERE IF COUNTINUING A RUN AT SPECIFIC COUNTER (CHUNK) IN ${win}
cntmax=1 #MAXIMUM NUMBER OF CHUNKS PER WINDOW


for ((i=$win;i<=$winmax;i++)); do
    cnt=${icnt} 
    while [ $cnt -le $cntmax ]; do
        pcnt=$(( cnt - 1 ))
        pwin=$(( i - 1 ))
        rc=$(awk "BEGIN {printf \"%.2f\", ${rci} + ((${i} - 1) * ${rcdel})}")
        scale=$(awk "BEGIN {printf \"%.6f\", 1 - ((2*($rc - $rc_mid)/($rcf - $rci))^2)}")
        kumb=$(awk "BEGIN {printf \"%.2f\", $kmin + ($kmax - $kmin)*$scale}")
        istep=${prod_step}_window_${i}_${cnt}

        
        if   [[ ${cnt} -eq 1 && ${i} -eq 1 ]]; then
            qrst=0
			pstep=${equi_prefix}
        elif [[ ${cnt} -eq 1 && ${i} -gt 1 ]]; then
            qrst=1
            pstep=${prod_step}_window_${pwin}_${cntmax}
        elif [[ ${cnt} -gt 1  ]]; then
            qrst=1
            pstep=${prod_step}_window_${i}_${pcnt}
        fi

        $charmm cnt=${cnt} mdcnt=${cnt} mdqrst=${qrst} mdwin=${i} mdpcnt=${pcnt} mdpwin=${pwin} mdrc=${rc} mdkumb=${kumb} mdpstep=${pstep} mdistep=${istep}  ${qmpackage}=1 < "${prod_prefix}.inp" > "${istep}.out"
        cnt=$(( cnt + 1 ))
    done
done 

